#!/bin/bash
if [ -z "${HAXEPATH}" ]; then
  export HAXEPATH=${0%/*}
fi
if [ -z "${NEKOPATH}" ]; then
  export NEKOPATH=${0%/*}/../neko
fi
if [ -z "${HAXELIB_PATH}" ]; then
  export HAXELIB_PATH=${0%/*}/../../../../.haxelib
fi
export PATH=$HAXEPATH:$NEKOPATH:$PATH
export HAXE_STD_PATH=$HAXEPATH/std
export DYLD_FALLBACK_LIBRARY_PATH=$NEKOPATH
"${0%/*}"/haxelib-bin "$@"