#!/bin/bash
SCRIPT_PATH=$(readlink -f "${BASH_SOURCE[0]}")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
if [ -z "${HAXEPATH}" ]; then
  export HAXEPATH=$SCRIPT_DIR
fi
if [ -z "${NEKOPATH}" ]; then
  export NEKOPATH=$SCRIPT_DIR/../neko
fi
if [ -z "${HAXELIB_PATH}" ]; then
  export HAXELIB_PATH=$SCRIPT_DIR/../../../../.haxelib
fi
export PATH=$HAXEPATH:$NEKOPATH:$PATH
export HAXE_STD_PATH=$HAXEPATH/std
export DYLD_FALLBACK_LIBRARY_PATH=$NEKOPATH
"$SCRIPT_DIR"/haxelib-bin "$@"